name: Java CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 20
      uses: actions/setup-java@v2
      with:
        java-version: '20'
        distribution: 'adopt'

    - name: Setup Gradle
      uses: gradle/setup-gradle@v8.6.0

    - name: Build with Gradle Wrapper
      run: ./program/gradlew build

    - name: Run tests
      run: ./program/gradlew test
